name: Kaggle
on: 
  workflow_dispatch:
  push:
      branches:
          - main
jobs:
  testitout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to Kaggle
      - uses: osbm/kaggle-login@main
        with:
          KAGGLE_USERNAME: mh0386
          KAGGLE_KEY: {{ secrets.KAGGLE_KEY }}
      - name: Use kaggle api to list datasets
        run: |
          kaggle datasets list
