name: Kaggle
on: 
  workflow_dispatch:
  push:
      branches:
          - main
jobs:
  pushToKaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/README.md') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Upload Dataset
        uses: jaimevalero/push-kaggle-dataset@v3.2
        env:
          KAGGLE_USERNAME: mh0386
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id:  "mh0386/seismic-data"
          title: "Seismic Data"
          files:  data
          is_public: false
