name: Kaggle
on: 
  workflow_dispatch:
  push:
      branches:
          - main
jobs:
  pushToKaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Upload datasets
        uses: jaimevalero/push-kaggle-dataset@v3.2
        env:
          KAGGLE_USERNAME: mh0386
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id:  "mh0386/seismic-data"
          title: "Seismic Data"
          files:  data
          is_public: false
      - name: Use kaggle api to list datasets
        run: |
          kaggle datasets list
